[package]
name = "basic-git-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
git2 = "0.20.2"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.6", features = ["cors"] }
